from .nodes import NODE_CLASS_MAPPINGS as _N, NODE_DISPLAY_NAME_MAPPINGS as _D
from .nodes_train import NODE_CLASS_MAPPINGS as _TN, NODE_DISPLAY_NAME_MAPPINGS as _TD
NODE_CLASS_MAPPINGS = {**_N, **_TN}; NODE_DISPLAY_NAME_MAPPINGS = {**_D, **_TD}
WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
